export const SkillsetItems = [
    { iconName: "devicon-javascript-plain " },
    { iconName: "devicon-nodejs-plain-wordmark " },
    { iconName: "devicon-express-original-wordmark" },
    { iconName: "devicon-react-original-wordmark" },
    { iconName: "devicon-mongodb-plain-wordmark" },
    { iconName: "devicon-bootstrap-plain-wordmark" },
    { iconName: "devicon-css3-plain-wordmark" },
    { iconName: "devicon-drupal-plain-wordmark" },
    { iconName: "devicon-html5-plain" },
    { iconName: "devicon-jquery-plain" },
    { iconName: "devicon-materialui-plain" },
    { iconName: "devicon-mysql-plain" },
    { iconName: "devicon-oracle-original" },
    { iconName: "devicon-php-plain" },
    { iconName: "devicon-postgresql-plain-wordmark" },
    { iconName: "devicon-typescript-plain" },
    { iconName: "devicon-wordpress-plain-wordmark" },
    { iconName: "cib-graphql" },
    { iconName: "cib-coreui-c" }
]

export const ToolsItems = [
    { iconName: "cib-visual-studio-code" },
    { iconName: "cib-visual-studio" },
    { iconName: "cib-postman" },
    { iconName: "cib-heroku" },
    { iconName: "devicon-git-plain"},
    { iconName: "devicon-github-original"},
    { iconName: "devicon-vim-plain"},
    { iconName: "devicon-photoshop-plain" },
    { iconName: "cib-filezilla" },
    { iconName: "cib-google-ads" },
    { iconName: "cib-unity" },
]